### ISSUE TITLE
node app.js throws "an undhandled error event"

### ISSUE THREAD

**Issue by shrish-bhargav** [RUDisCOOL/DE_Project#3]
steps to reproduce: 
1) checkout to master branch
2) try node app.js after doing npm i

Here is the logged message : 
> node app.js
Hey I am running on port 5500
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: Access denied for user ''@'localhost'
    at Packet.asError (/home/shrish/DE_Project/node_modules/mysql2/lib/packets/packet.js:728:17)
    at ClientHandshake.execute (/home/shrish/DE_Project/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/home/shrish/DE_Project/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/home/shrish/DE_Project/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/home/shrish/DE_Project/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/shrish/DE_Project/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
Emitted 'error' event on PoolConnection instance at:
    at PoolConnection._notifyError (/home/shrish/DE_Project/node_modules/mysql2/lib/connection.js:252:12)
    at PoolConnection._handleFatalError (/home/shrish/DE_Project/node_modules/mysql2/lib/connection.js:183:10)
    at PoolConnection.handlePacket (/home/shrish/DE_Project/node_modules/mysql2/lib/connection.js:491:12)
    at PacketParser.onPacket (/home/shrish/DE_Project/node_modules/mysql2/lib/connection.js:97:12)
    [... lines matching original stack trace ...]
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_ACCESS_DENIED_NO_PASSWORD_ERROR',
  errno: 1698,
  sqlState: '28000',
  sqlMessage: "Access denied for user ''@'localhost'",
  sql: undefined,
  fatal: true
}

Node.js v20.11.1

**Comment by vvaibhavv11** [comment]
This is the problem of your computer doesn't have permission to access database sole that first and don't forget to close the issue
